version: "3.7"

# To reload Caddyfile without restarting the entire container:
# docker exec -w /etc/caddy caddy caddy reload

services:
  caddy:
    # image: caddy:2.3.0-alpine
    build: ./caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    # You have to put a passwords.env next to this compose file
    # Make sure the users match the caddyfile
    env_file:
      - passwords.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/data:/data
      - ./volumes/config:/config
      - /media/external/shared/web:/shared-files:ro
