version: "3.3"
services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    restart: unless-stopped
    user: 1000:1000
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user greg --rc-pass ${RC_PASS} --config /data/.config/rclone.conf --cache-dir /data/.cache
    ports:
      - "5572:5572"
      - "53682:53682"
    volumes:
      - /media/external/shared/backups/rclone:/data
