global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP 
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [as-collected]
      #
      # server name for this prometheus - the default is the client IP
      # for Netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:19999']

  - job_name: 'jellyfin'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8096']
    # Jellyfin doesn't prefix :/
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'jellyfin_${1}'
        target_label: __name__
  
  - job_name: 'transmission'
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:19091'] # See the torrenting docker-compose
  
  - job_name: 'caddy'
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:2019']
  
  - job_name: 'pihole'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9617']
